import type { Payload } from "payload";

/**
 * Carried over from TARIFF, TARIFF_NOTES, MEALS_INCLUDED, MEALS_EXTRA and
 * STAY_INFO in src/lib/site.ts as of 2026-07-25.
 *
 * Provenance: per-person, per-night rates come from the
 * nexttripbooking.com / bookingnexttrip.com listings for this property (see
 * README); meals and check-in times come from the client's own info sheet.
 * These rates can change seasonally — confirm by phone before publishing.
 *
 * The notes below were generated by string interpolation in site.ts. They are
 * now plain editable text, so they no longer track the meals list
 * automatically.
 */
export async function seedTariff(payload: Payload): Promise<void> {
  const existing = await payload.findGlobal({ slug: "tariff", depth: 0 });
  if (existing?.rates?.length) {
    payload.logger.info("seed: tariff already populated, skipping");
    return;
  }

  await payload.updateGlobal({
    slug: "tariff",
    data: {
      title: "One per-person price, *meals included*.",
      rates: [
        { name: "Triple sharing", amount: 1500, unit: "per person / night" },
        { name: "4–5 sharing", amount: 1400, unit: "per person / night" },
        {
          name: "Camping tent",
          amount: 1200,
          unit: "per person / night",
          note: "common washroom",
        },
      ],
      mealsIncluded: [
        { value: "Morning tea" },
        { value: "Breakfast" },
        { value: "Lunch" },
        { value: "Evening tea & snacks" },
        { value: "Dinner" },
      ],
      mealsExtra: [
        { value: "Barbecue (BBQ)" },
        { value: "Extra snacks" },
        { value: "Special dishes" },
      ],
      checkIn: "12:00 PM",
      checkOut: "11:00 AM",
      firstLight: "05:30 IST",
      notes: [
        {
          value:
            "Tariff includes morning tea, breakfast, lunch, evening tea & snacks, dinner.",
        },
        {
          value:
            "Barbecue (BBQ), Extra snacks, Special dishes available on request at extra cost.",
        },
        { value: "Check-in from 12:00 PM · Check-out by 11:00 AM." },
        { value: "Call ahead to confirm current rates and availability." },
      ],
      reserveHeading: "One phone call is all it takes.",
      _status: "published",
    },
    context: { disableRevalidate: true },
  });

  payload.logger.info("seed: tariff populated");
}
