/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'room-types': RoomType;
    'hotel-rooms': HotelRoom;
    'daily-availability': DailyAvailability;
    bookings: Booking;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'room-types': RoomTypesSelect<false> | RoomTypesSelect<true>;
    'hotel-rooms': HotelRoomsSelect<false> | HotelRoomsSelect<true>;
    'daily-availability': DailyAvailabilitySelect<false> | DailyAvailabilitySelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    rooms: Room;
    experiences: Experience;
    gallery: Gallery;
    tariff: Tariff;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    tariff: TariffSelect<false> | TariffSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Room-status access is limited to authenticated staff and managers in this admin panel.
   */
  role: 'manager' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Reusable room configurations. Add a type here before adding its rooms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-types".
 */
export interface RoomType {
  id: number;
  /**
   * For example: 4-Sharing or 2-Sharing.
   */
  name: string;
  /**
   * Maximum guests for one whole room. Beds are not booked separately.
   */
  capacity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each record is one bookable room. Mark a room inactive to remove it from future daily availability.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotel-rooms".
 */
export interface HotelRoom {
  id: number;
  /**
   * A stable room identifier, for example 101 or Cottage A.
   */
  roomNumber: string;
  roomType: number | RoomType;
  /**
   * Only active rooms appear in the daily availability board.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per date. Bookings update these room statuses automatically; use this board for manual changes and maintenance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-availability".
 */
export interface DailyAvailability {
  id: number;
  /**
   * Create exactly one availability board for each calendar date.
   */
  date: string;
  /**
   * Select a date, save once, then update only the room status and note below.
   */
  availability?:
    | {
        room: number | HotelRoom;
        /**
         * Set automatically from the Rooms list.
         */
        roomNumber: string;
        bookingRecordID?: string | null;
        status: 'available' | 'booked' | 'maintenance';
        /**
         * Optional guest, group, or operational note. Clear it when the room becomes Available again.
         */
        guestNotes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Book one or more whole rooms for a guest or group. Cancelling releases every booked night automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  customerName: string;
  /**
   * Use the number staff should call for this booking.
   */
  customerPhone: string;
  /**
   * Select every whole room this guest or group is taking.
   */
  rooms: (number | HotelRoom)[];
  checkIn: string;
  /**
   * The room becomes available again on this date.
   */
  checkOut: string;
  /**
   * Set to Cancelled to release all rooms and dates without deleting the booking record.
   */
  status: 'confirmed' | 'cancelled';
  /**
   * Optional internal note for the booking.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'room-types';
        value: number | RoomType;
      } | null)
    | ({
        relationTo: 'hotel-rooms';
        value: number | HotelRoom;
      } | null)
    | ({
        relationTo: 'daily-availability';
        value: number | DailyAvailability;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-types_select".
 */
export interface RoomTypesSelect<T extends boolean = true> {
  name?: T;
  capacity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotel-rooms_select".
 */
export interface HotelRoomsSelect<T extends boolean = true> {
  roomNumber?: T;
  roomType?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-availability_select".
 */
export interface DailyAvailabilitySelect<T extends boolean = true> {
  date?: T;
  availability?:
    | T
    | {
        room?: T;
        roomNumber?: T;
        bookingRecordID?: T;
        status?: T;
        guestNotes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  customerName?: T;
  customerPhone?: T;
  rooms?: T;
  checkIn?: T;
  checkOut?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * The full-screen opening photograph. Use a wide landscape — it is cropped to fill the whole screen on every device.
   */
  backgroundImage: number | Media;
  /**
   * First line of the big headline, e.g. Sunrise
   */
  headlineLine1: string;
  /**
   * Second line of the big headline, e.g. Viewpoint
   */
  headlineLine2: string;
  /**
   * A one-character flourish shown in teal after the headline, normally a full stop. Leave empty for none.
   */
  headlineAccent?: string | null;
  subhead: string;
  /**
   * Text on the button, e.g. Call to book. The button always jumps to the Tariff section.
   */
  ctaLabel: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  /**
   * Section heading. Wrap one word in *asterisks* to show it in the celadon accent, e.g. All of them face *east*. NOTE: this heading mentions how many rooms there are — update it if you add or remove a room below.
   */
  title: string;
  /**
   * At least one room type is required. Drag to reorder — this is the order guests scroll through.
   */
  items: {
    /**
     * e.g. "4-Sharing Rooms"
     */
    name: string;
    /**
     * e.g. "6 rooms" or "pitched on request"
     */
    count: string;
    /**
     * e.g. "up to 4 guests per room"
     */
    occupancy: string;
    tagline: string;
    /**
     * Short chips shown under the description.
     */
    features: {
      value: string;
      id?: string | null;
    }[];
    image: number | Media;
    id?: string | null;
  }[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  /**
   * Section heading. Wrap one word in *asterisks* for the celadon accent. NOTE: this heading counts the cards below ("Six things worth leaving the veranda for.") — update it if you add or remove one.
   */
  title: string;
  /**
   * At least one is required. Drag to reorder — cards stack in this order as the visitor scrolls.
   */
  items: {
    title: string;
    body: string;
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * Small location line at the bottom of every card.
   */
  cardFooterLabel: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Section heading. Wrap one word in *asterisks* for the celadon accent.
   */
  title: string;
  /**
   * At least one photo is required. Drag to reorder. The LAST photo is always shown full width across the page, so give that slot a wide landscape rather than an interior.
   */
  photos: {
    image: number | Media;
    /**
     * Shown over the bottom-left of the photo, like a gallery wall label.
     */
    caption: string;
    id?: string | null;
  }[];
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariff".
 */
export interface Tariff {
  id: number;
  /**
   * Section heading. Wrap one word in *asterisks* for the celadon accent.
   */
  title: string;
  /**
   * One row per type of sharing. Confirm current rates by phone before publishing — these change seasonally.
   */
  rates: {
    /**
     * Type of sharing, e.g. "Triple sharing"
     */
    name: string;
    /**
     * Just the number, no ₹ and no commas — 1500, not ₹1,500. The rupee symbol and comma are added automatically.
     */
    amount: number;
    unit: string;
    /**
     * Optional small print, e.g. "common washroom".
     */
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * Shown beneath the rates. Keep this clear that online prices are approximate and should be confirmed by calling the homestay.
   */
  rateDisclaimer: string;
  /**
   * Shown under "Included in every stay". The "All N meals included" chip counts these automatically.
   */
  mealsIncluded: {
    value: string;
    id?: string | null;
  }[];
  /**
   * Shown under "Available on request, extra cost". May be left empty.
   */
  mealsExtra?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "12:00 PM"
   */
  checkIn: string;
  /**
   * e.g. "11:00 AM"
   */
  checkOut: string;
  /**
   * Shown on the Reserve chip, e.g. "05:30 IST"
   */
  firstLight: string;
  /**
   * These do NOT update automatically. If you change the meals or the check-in and check-out times above, edit these notes to match.
   */
  notes: {
    value: string;
    id?: string | null;
  }[];
  reserveHeading: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The FIRST number in this list is the one shown in the site header, the floating call button, and Google's search listing. Drag to reorder.
   */
  bookingPhones: {
    /**
     * For example "Bookings" or "Bookings (alt.)".
     */
    label: string;
    /**
     * Write it the way it should appear, e.g. +91 98006 37784. The tap-to-call link is generated automatically.
     */
    number: string;
    id?: string | null;
  }[];
  /**
   * The local driver shown in Getting Here and the footer — not the homestay itself.
   */
  transportName: string;
  transportPhones: {
    number: string;
    id?: string | null;
  }[];
  /**
   * Shown in the hero and footer, and parsed into the site's map metadata for Google. Keep the format "26.9369° N, 88.4039° E".
   */
  coordinates: string;
  /**
   * Approximate values keep the "≈" prefix rather than presenting a guess as certain.
   */
  altitude: string;
  region: string;
  /**
   * Shown in the footer and in the site's search-engine metadata.
   */
  address: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  backgroundImage?: T;
  headlineLine1?: T;
  headlineLine2?: T;
  headlineAccent?: T;
  subhead?: T;
  ctaLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        name?: T;
        count?: T;
        occupancy?: T;
        tagline?: T;
        features?:
          | T
          | {
              value?: T;
              id?: T;
            };
        image?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  cardFooterLabel?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariff_select".
 */
export interface TariffSelect<T extends boolean = true> {
  title?: T;
  rates?:
    | T
    | {
        name?: T;
        amount?: T;
        unit?: T;
        note?: T;
        id?: T;
      };
  rateDisclaimer?: T;
  mealsIncluded?:
    | T
    | {
        value?: T;
        id?: T;
      };
  mealsExtra?:
    | T
    | {
        value?: T;
        id?: T;
      };
  checkIn?: T;
  checkOut?: T;
  firstLight?: T;
  notes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  reserveHeading?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  bookingPhones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  transportName?: T;
  transportPhones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  coordinates?: T;
  altitude?: T;
  region?: T;
  address?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}